export const APIConst = {
    TRANS: 'dmo/transactions/302',
    MAIN_TRANS: 'dmo/dpentrysheet/201',
    MAIN_TRANS_2: 'dmo/dpentrysheet/202',
    MAIN_TRANS_SUBMIT: 'dmo/dpentrysheet/101',
    MAIN_TRANS_BY_ID: 'dmo/dpentrysheet/301',
    NSS_LOAN_RECEIVED: 'dmo/nssfloanreceived/201',
    NSS_LOAN_RECEIVED_DETAILS: 'dmo/nssfloanreceived/301',
    NSS_LOAN_ADD: 'dmo/nssfloanreceived/101',
    NSS_LOAN_PAYBLE_DET: 'dmo/nssfloanrepayment/201',
    NSS_LOAN_RESHEDULE_DET: 'dmo/nssfloanrepayment/201',
    MARKET_LOAN_RECEIVED: 'dmo/dpentrysheet/marketloan',
    MARKET_LOAN_RECEIVED_DETAILS: 'dmo/marketloanreceived/301',
    MARKET_LOAN_SAVE: 'dmo/marketloan/101',
    MARKET_LOAN_APPROVED_LIST: 'dmo/marketloan/201',
    NSS_LOAN_REPAYMENT_SAVE: 'dmo/nssfloanrepayment/101',
    NSS_LOAN_REPAYMENT_SCH: 'dmo/nssfloanreceived/202',
    ADVICE_MASTER_LISTING:'dmo/adviceagency/201',
    ADVICE_MASTER_ADD:'dmo/adviceagency/101',
    GOI_DEPARTMENT_MINISTRY_NAME_MASTER:'dmo/deparmentministry/201',
    GOI_DEPARTMENT_MINISTRY_NAME_MASTER_ADD:'dmo/deparmentministry/101',
    GOI_LOAN_PURPOSE_MASTER:'dmo/loanpurpose/201',
    GOI_LOAN_PURPOSE_MASTER_ADD:'dmo/loanpurpose/101',
    INSTITUTE_MASTER:'dmo/instituemaster/201',
    INSTITUTE_MASTER_ADD:'dmo/instituemaster/101',
    SECURITY_MASTER:'dmo/secuirtyemaster/201',
    SECURITY_MASTER_ADD:'dmo/secuirtyemaster/101',
    WMA_MASTER:'dmo/wmatype/201',
    WMA_MASTER_ADD:'dmo/wmatype/101',
    FINANCIAL_YEAR:'dmo/guarantee/entry/308',
    WAY_OF_FLOATATION:'edp/lulookupinfo/getbyparentlookupid',
    GET_ALL_REPAYMENT_BY_ADVICE_NO:'dmo/marketloan/202',
    SEARCH_FOR_REPAYMENT_BY_ADVICE_No:'dmo/marketloan/searchRepay',
    Update_Repayment:'dmo/marketloanrepayment/401',
    PRESS_COMMUNIQUE_FOR_PRINCIPAL_PAYMENT:'dmo/marketloan/search'
    
}